name: Build LostKit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka pyqt6

    - name: Prepare Dependency Walker
      run: |
        mkdir "%LOCALAPPDATA%\Nuitka\Nuitka\Cache\depends\x86_64"
        curl -L -o "%LOCALAPPDATA%\Nuitka\Nuitka\Cache\depends\x86_64\depends.zip" "https://dependencywalker.com/depends22_x64.zip"
        powershell -Command "Expand-Archive '%LOCALAPPDATA%\Nuitka\Nuitka\Cache\depends\x86_64\depends.zip' '%LOCALAPPDATA%\Nuitka\Nuitka\Cache\depends\x86_64\'"

    - name: Build with Nuitka
      
      run: |
        python -m nuitka main.py --onefile --standalone --enable-plugin=pyqt6 --windows-icon-from-ico=icon.ico --windows-console-mode=disable --include-data-files=icon.ico=icon.ico --include-data-files=button.jpg=button.jpg --include-data-files=RuneScape-Quill.ttf=RuneScape-Quill.ttf --include-data-files=icons/*=icons/ --output-filename=LostKit.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: LostKit
        path: LostKit.exe
